### ISSUE TITLE
No code

### ISSUE THREAD

**Issue by kayi1224** [TwoSquirrels/RIZE#1]
コードが表示されませんがバグですか?

**Comment by TwoSquirrels** [comment]
コードはこれから書き始めます

**Comment by TwoSquirrels** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ホームページ](https://trello.com/c/FKXfQkLe/3-%E3%83%9B%E3%83%BC%E3%83%A0%E3%83%9A%E3%83%BC%E3%82%B8)
